theme: jekyll-theme-minimal
title: Bongsub Song
description: Researcher / Ph.D. at ETRI | Robotics & AI
logo: /assets/profile.jpg # 여기에 프로필 사진 파일 경로를 넣으세요 (예: /assets/profile.jpg)
show_downloads: false
# google_analytics: # 구글 애널리틱스 ID가 있다면 여기에 넣으세요
